### PR TITLE
Added ability to ask follow up questions

### PR DESCRIPTION
**Pull request by rishsriv**
I added the functionality but it doesn't look as good. Manas will let you choose if you want to keep this as is, or want to make some changes before merging.

Also, have not published to npm yet.

### CODE REVIEW

**Comment by man-shar** [comment]
First look UI improvements seem to be:
1. When you ask a new question, show loading where the question actually is instead of at the bottom
2. Make the view more compact by allowing for collapsing an answer.
3. Once we make the view compact, the "threads" part of it could have more left indents.

**Comment by rishsriv** [comment]
Good points! Would you be okay with taking these? I'm hoping to finish up work around making the customer onboarding process easier this week!

**Comment by man-shar** [comment]
Oh yeah yeah, that's what I meant. Will implement!

**Comment by man-shar** [comment]
hey hey, have made a lot of style changes. could test and lmk how it looks?

maybe a few more UX fixes can be made, but will wait for your feedback/ideas too:
1. can we do parallel requests without websockets?? do we need to disable all buttons when there's a request happening?
2. I don't know if the main search bar should be at the bottom or the top. If we change it to top, the questions will have to be sorted in latest _first_.
3. perhaps there should be a "collapse all tables" shortcut.
4. The "click to show/hide table" text is vertically off center when collapsed.

**Comment by rishsriv** [comment]
Manas this looks amazing. Thank you! Just tested this thoroughly and couldn't find bugs

- We can remove websockets for now, actually. Think they are better suited for agents anyway!
- I like having the main search bar at the bottom. Do you think it makes sense to have it "sticky" at the bottom of the viewport, or should we always have it at the bottom of the window? Can see good arguments for both – happy to let you have the final say

> perhaps there should be a "collapse all tables" shortcut

Nah I think this is good! But feel free to add if you would like

> The "click to show/hide table" text is vertically off center when collapsed.

Ah this is alright! Honestly couldn't tell even when I looked :)

Will merge and push to npm! Thanks for doing this!

**Pull request merged**
